export const questions = [
  {
    q: "What is the core challenge that Off-Policy Evaluation (OPE) tries to solve?",
    choices: [
      "How to train a policy faster by reusing data from many different policies",
      "How to estimate the expected reward of a target policy π_e using data collected by a different behavior policy π_b, without running π_e in the real environment",
      "How to compute the optimal policy when the reward function is unknown",
      "How to reduce variance in on-policy Monte Carlo returns by importance sampling"
    ],
    answer: 1,
    explain: "OPE asks: given a logged dataset {(a_t, r_t)} generated by π_b, what would the value V(π_e) have been if π_e had acted instead? This matters whenever deploying π_e is expensive, risky, or irreversible. Choice A describes data reuse in training, not evaluation. Choice C is offline RL / inverse reward learning. Choice D is an on-policy method, not OPE."
  },
  {
    q: "The Importance Sampling (IS) estimator V̂_IS = (1/n) Σ_t [π_e(a_t)/π_b(a_t)] · r_t is unbiased under which conditions? Select all that apply.",
    choices: [
      "The behavior policy π_b must have support everywhere π_e has support: π_e(a|s) > 0 ⟹ π_b(a|s) > 0",
      "The logged actions and rewards must be unconfounded: no hidden variables affected both the logger's action choice and the reward",
      "The target policy π_e must be deterministic",
      "The importance weights π_e/π_b must be correctly specified — using a wrong π_b makes the estimator biased regardless of sample size"
    ],
    answer: [0, 1, 3],
    explain: "IS is unbiased when (A) coverage holds — you cannot reweight actions the logger never took; (B) logging is unconfounded — if a hidden variable Z simultaneously drove the logger's arm choice and the reward, the recorded propensity is wrong and the reweighting is invalid; (D) the propensity model is correctly specified — a misspecified π_b produces biased weights that do not vanish with n. Choice C is false: IS is unbiased for stochastic target policies too, provided the ratio is computed correctly."
  },
  {
    q: "The Doubly Robust (DR) estimator combines a Direct Method (DM) model with an IS correction: V̂_DR = V̂_DM + (1/n) Σ [w_t · (r_t − r̂(s_t,a_t))]. It is called 'doubly robust' because:",
    choices: [
      "It is unbiased if EITHER the outcome model r̂ is correctly specified OR the propensity model π_b is correctly specified (but not necessarily both)",
      "It applies two rounds of cross-fitting to debias both the outcome model and the propensity model",
      "It uses two separate datasets — one for training and one for evaluation — to avoid overfitting",
      "It is robust to hidden confounding even when neither model is correctly specified"
    ],
    answer: 0,
    explain: "Double robustness means: if the outcome model r̂ is exactly right, the IS correction term has expectation 0 (residuals are mean-zero), and V̂_DR = V̂_DM which is unbiased. If the propensity model π_b is exactly right, the IS term corrects the DM bias even when r̂ is wrong. You only need one of the two to be correctly specified. Choice D is the critical misconception: DR does NOT protect against hidden confounding. When the hidden confounder biases π_b, BOTH the DM and IS components inherit that bias, as the module's confounding slider demonstrates."
  },
  {
    q: "A researcher raises the 'hidden confounding strength' slider to 2.5 in the OPE module, then runs 200 bootstrap datasets. She observes that the IS, WIS, and DR estimators all drift away from the gold truth line. She concludes that 'doubly robust just needs more data.' What is wrong with her conclusion?",
    choices: [
      "She should use more bins for the bootstrap histogram",
      "The bias from hidden confounding does not shrink with sample size — it is a systematic misspecification of π_b caused by the confounder, not sampling noise. More data makes the biased estimate more precise, not more accurate",
      "DR would recover if she also randomized the target policy π_e",
      "She should switch to the Direct Method since it is unaffected by propensity misspecification"
    ],
    answer: 1,
    explain: "The confounding slider preferentially drops far-distance treated units from the log. The propensity we record (the empirical π_b from the full RCT) is now wrong — the subsampled data look as if treated units are closer on average. This systematic error in the propensity model makes the IS weights incorrect, and that incorrectness is a constant bias, not variance. Doubling n makes the wrong estimate more tightly concentrated around the wrong value. Choice C doesn't help — π_b is still misspecified. Choice D is also false: the DM estimator uses only the logged data, so if the log is a biased sample, the DM outcome model is also biased."
  },
  {
    q: "In the Thornton (AER 2008) module, the target policy π_e is 'always treat' (any=1 for everyone). At hidden confounding = 0, the IS bootstrap distribution is centered on the gold truth line V(π_e) = E[got | any=1]. Which feature of the Thornton study design makes this possible?",
    choices: [
      "The Thornton study used stratified sampling by distance to the VCT center, so propensities are exactly 0.5 for all subgroups",
      "Cash incentives were randomly assigned in the RCT, so the recorded behavior propensity π_b(any=1) is the true probability of treatment — the correctly specified propensity and absence of hidden confounders make IS exactly unbiased",
      "The outcome variable 'got' (learned HIV status) is binary, which makes IS weights exactly equal to 1",
      "The target policy and behavior policy are close in KL divergence, keeping importance weights near 1 and variance low"
    ],
    answer: 1,
    explain: "The Thornton study randomized incentive assignment, so treatment (any=1) is statistically independent of all covariates including distance to the VCT center. The empirical fraction treated in the logged data equals the true randomization probability. With a correctly specified π_b and no hidden confounders in the original log, the IS estimator is exactly unbiased — its bootstrap distribution centers on the gold truth line. Choice A is incorrect — propensities are not 0.5 and the study did not stratify by distance. Choice C is wrong — binary outcomes do not make IS weights equal to 1; the weights depend on the propensity ratio. Choice D describes a variance property, not unbiasedness."
  }
];
