export const questions = [
  {
    q: "What is the key intuition behind Prior-Data Fitted Networks (PFNs) for causal inference? Pick the best one-sentence summary.",
    choices: [
      "A PFN fine-tunes a pre-trained language model on each new dataset to estimate treatment effects.",
      "A PFN is pre-trained once on a large distribution of synthetic causal worlds (the prior), so that on any new dataset it can estimate the treatment-effect curve in a single forward pass — no per-dataset retraining.",
      "A PFN replaces the propensity score with a neural network trained on the observed data.",
      "A PFN learns the causal graph structure from data and then applies the backdoor formula automatically."
    ],
    answer: 1,
    explain: "The PFN paradigm (Müller et al. ICLR 2022, extended to causal inference in CausalPFN 2025 and CausalFM ICLR 2026) is: amortize the hard work into pre-training on a synthetic prior, then perform <em>in-context inference</em> — a single forward pass at test time, with no gradient updates on the new dataset. A describes fine-tuning, which is the opposite. C describes a standard propensity-score model that trains on each dataset from scratch. D describes a structure-learning pipeline, not a PFN."
  },
  {
    q: "The PFN prior in the module is explicitly described as <strong>synthetic by design</strong>. Which of the following correctly explains why this is inherent to the PFN approach, and what the real test set is?",
    choices: [
      "Synthetic priors are a limitation — ideally PFNs would pre-train on real observational datasets; the test set here is also synthetic.",
      "The prior must be synthetic because PFNs perform Bayesian inference: the prior is the distribution over causal worlds from which the model learns the <em>skill</em> of effect estimation; the test set is the real IHDP benchmark (Hill 2011) with real infant covariates.",
      "Synthetic priors are used only to avoid copyright issues with real data; any large real-data corpus would work just as well.",
      "The synthetic prior means the PFN is only valid on simulated data and cannot generalize to real data."
    ],
    answer: 1,
    explain: "PFNs implement amortized Bayesian inference by in-context learning (Müller et al. 2022): the synthetic SCM prior is the distribution P(datasets) over which the model is trained to approximate posterior predictive distributions. This is not a limitation but a design feature — training on synthetic priors lets the model learn the general skill of causal estimation, which then generalizes. The test set in this module is the real IHDP benchmark (semi-synthetic: real covariates x1–x25, known potential outcomes μ₀, μ₁), enabling exact PEHE scoring. A inverts the logic. C misattributes the choice to copyright. D is falsified by the module itself, which shows the PFN generalizing to real IHDP data."
  },
  {
    q: "PEHE (Precision in Estimation of Heterogeneous Effects) is the metric used to evaluate PFN vs. T-learner performance on IHDP. Which of the following statements about PEHE are correct? (Select all that apply.)",
    choices: [
      "PEHE = √(E[(τ̂(x) − τ(x))²]), the root-mean-square error of the estimated CATE relative to the true ITE.",
      "A lower PEHE is better — it means the estimated treatment-effect curve is closer to the true curve.",
      "PEHE can only be computed on real-world data where we observe both Y(0) and Y(1) for each unit.",
      "IHDP allows exact PEHE scoring because the true ITE = μ₁ − μ₀ is known from the semi-synthetic simulation."
    ],
    answer: [0, 1, 3],
    explain: "A is correct: PEHE is the RMSE of individual effect predictions against the ground truth. B is correct: lower PEHE means better effect-curve recovery. D is correct and is why IHDP is such a useful benchmark — the potential outcomes μ₀(x) and μ₁(x) were generated by a known function, so the true ITE is available. C is false and is actually the key point: in real observational data you <em>never</em> observe both potential outcomes for the same unit (the fundamental problem of causal inference), which is exactly why benchmarks like IHDP are needed — they provide the ground truth that real-world data cannot."
  },
  {
    q: "A critic argues: 'The T-learner baseline trains two separate outcome models μ̂₀ and μ̂₁ on the same IHDP test data, so comparing it to the PFN is unfair — the T-learner sees the test data during training, while the PFN was pre-trained on synthetic data.' What is the correct response to this criticism?",
    choices: [
      "The critic is right; a fair comparison would pre-train the T-learner on a separate held-out sample.",
      "The comparison is intentional and reveals the PFN's key advantage: the T-learner must expend many gradient steps on the new data and still may underfit in sparse regions, while the PFN uses the new data only as an in-context prompt and answers in a single forward pass — demonstrating amortized efficiency.",
      "The PFN also trains on the test data during its forward pass, so both methods are equally data-hungry.",
      "The T-learner should be considered the better method because it uses the actual data distribution."
    ],
    answer: 1,
    explain: "The comparison is the whole point. The T-learner represents the classical paradigm: a new dataset arrives, you train from scratch. The PFN represents the amortized paradigm: no per-dataset training at all — inference is a forward pass, treating the dataset as a context (like few-shot examples in a language model). The module measures whether amortization costs accuracy (PEHE). A misunderstands the goal — we want to compare amortized vs. per-dataset training, not equalize training conditions. C is wrong: the PFN's forward pass does not update any weights; reading input data is not the same as training on it. D sidesteps the amortization question entirely."
  },
  {
    q: "In the module, the x-axis of the test-data plot is labeled <em>x₁ — birth-weight z-score (IHDP, projected to 1-D)</em>. Why is x₁ used as the single projected covariate, and what does the real IHDP dataset actually contain?",
    choices: [
      "x₁ is the only variable recorded in IHDP; the other dimensions are noise.",
      "x₁ (standardised birth-weight z-score) is chosen because it is the most predictive continuous covariate in IHDP; the full dataset has 25 covariates (x1–x25) for 747 infants, including health and family variables, with semi-synthetic potential outcomes μ₀ and μ₁ designed by Hill (2011).",
      "x₁ is a randomly selected covariate used only for visualization convenience, with no special predictive value.",
      "The IHDP dataset has only two variables: x₁ and the treatment indicator."
    ],
    answer: 1,
    explain: "The real IHDP benchmark (Hill 2011) has 747 infant observations, 25 pre-treatment covariates (birth weight, neonatal health indicators, family SES variables, etc.), a binary treatment (specialist home visits), and semi-synthetic potential outcomes created by applying a known response function so that the true ITE = μ₁ − μ₀ is available. The module uses x₁ (birth-weight z-score) as the 1-D projection because it is empirically the most predictive covariate for the outcome, making a 1-D CATE plot informative. A, C, and D are all false about the dataset's scope."
  }
];
